/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Attributes.h.zapt

#pragma once

#include <app/ConcreteAttributePath.h>
#include <app/data-model/DecodableList.h>
#include <app/data-model/List.h>
#include <app/data-model/Nullable.h>
#include <app/util/basic-types.h>
#include <lib/core/TLV.h>
#include <lib/support/BitMask.h>

#include <clusters/shared/Attributes.h>
#include <clusters/shared/Enums.h>
#include <clusters/shared/Structs.h>

#include <clusters/PhotonSmart/AttributeIds.h>
#include <clusters/PhotonSmart/ClusterId.h>
#include <clusters/PhotonSmart/Enums.h>
#include <clusters/PhotonSmart/Structs.h>

namespace chip {
namespace app {
namespace Clusters {
namespace PhotonSmart {
namespace Attributes {

namespace HomeId {
struct TypeInfo
{
    using Type             = chip::app::DataModel::Nullable<chip::CharSpan>;
    using DecodableType    = chip::app::DataModel::Nullable<chip::CharSpan>;
    using DecodableArgType = const chip::app::DataModel::Nullable<chip::CharSpan> &;

    static constexpr ClusterId GetClusterId() { return Clusters::PhotonSmart::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::HomeId::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
    static constexpr size_t MaxLength() { return 150; }
};
} // namespace HomeId
namespace ShouldReboot {
struct TypeInfo
{
    using Type             = bool;
    using DecodableType    = bool;
    using DecodableArgType = bool;

    static constexpr ClusterId GetClusterId() { return Clusters::PhotonSmart::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::ShouldReboot::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace ShouldReboot
namespace MqttConfig {
struct TypeInfo
{
    using Type             = chip::app::Clusters::PhotonSmart::Structs::PhotonMQTTStruct::Type;
    using DecodableType    = chip::app::Clusters::PhotonSmart::Structs::PhotonMQTTStruct::DecodableType;
    using DecodableArgType = const chip::app::Clusters::PhotonSmart::Structs::PhotonMQTTStruct::DecodableType &;

    static constexpr ClusterId GetClusterId() { return Clusters::PhotonSmart::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::MqttConfig::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace MqttConfig
namespace GeneratedCommandList {
struct TypeInfo : public Clusters::Globals::Attributes::GeneratedCommandList::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::PhotonSmart::Id; }
};
} // namespace GeneratedCommandList
namespace AcceptedCommandList {
struct TypeInfo : public Clusters::Globals::Attributes::AcceptedCommandList::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::PhotonSmart::Id; }
};
} // namespace AcceptedCommandList
namespace AttributeList {
struct TypeInfo : public Clusters::Globals::Attributes::AttributeList::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::PhotonSmart::Id; }
};
} // namespace AttributeList
namespace FeatureMap {
struct TypeInfo : public Clusters::Globals::Attributes::FeatureMap::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::PhotonSmart::Id; }
};
} // namespace FeatureMap
namespace ClusterRevision {
struct TypeInfo : public Clusters::Globals::Attributes::ClusterRevision::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::PhotonSmart::Id; }
};
} // namespace ClusterRevision

struct TypeInfo
{
    struct DecodableType
    {
        static constexpr ClusterId GetClusterId() { return Clusters::PhotonSmart::Id; }

        CHIP_ERROR Decode(TLV::TLVReader & reader, const ConcreteAttributePath & path);

        Attributes::HomeId::TypeInfo::DecodableType homeId;
        Attributes::ShouldReboot::TypeInfo::DecodableType shouldReboot = static_cast<bool>(0);
        Attributes::MqttConfig::TypeInfo::DecodableType mqttConfig;
        Attributes::GeneratedCommandList::TypeInfo::DecodableType generatedCommandList;
        Attributes::AcceptedCommandList::TypeInfo::DecodableType acceptedCommandList;
        Attributes::AttributeList::TypeInfo::DecodableType attributeList;
        Attributes::FeatureMap::TypeInfo::DecodableType featureMap           = static_cast<uint32_t>(0);
        Attributes::ClusterRevision::TypeInfo::DecodableType clusterRevision = static_cast<uint16_t>(0);
    };
};
} // namespace Attributes
} // namespace PhotonSmart
} // namespace Clusters
} // namespace app
} // namespace chip
