/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Structs.ipp.zapt

#include <clusters/PhotonSmart/Structs.h>

#include <app/data-model/StructDecodeIterator.h>
#include <app/data-model/WrappedStructEncoder.h>

namespace chip {
namespace app {
namespace Clusters {
namespace PhotonSmart {
namespace Structs {

namespace PhotonInsightsParamsStruct {
CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kCoreDumpEnabled), coreDumpEnabled);
    encoder.Encode(to_underlying(Fields::kMinInterval), minInterval);
    encoder.Encode(to_underlying(Fields::kMaxInterval), maxInterval);
    encoder.Encode(to_underlying(Fields::kDropWifiLogs), dropWifiLogs);
    encoder.Encode(to_underlying(Fields::kReportMetrics), reportMetrics);
    encoder.Encode(to_underlying(Fields::kReportHeapMetrics), reportHeapMetrics);
    encoder.Encode(to_underlying(Fields::kHeapPollingInterval), heapPollingInterval);
    encoder.Encode(to_underlying(Fields::kHeapPollingCount), heapPollingCount);
    encoder.Encode(to_underlying(Fields::kReportWifiMetrics), reportWifiMetrics);
    encoder.Encode(to_underlying(Fields::kWifiPollingInterval), wifiPollingInterval);
    encoder.Encode(to_underlying(Fields::kWifiPollingCount), wifiPollingCount);
    encoder.Encode(to_underlying(Fields::kUsePolling), usePolling);
    encoder.Encode(to_underlying(Fields::kReportVariables), reportVariables);
    encoder.Encode(to_underlying(Fields::kReportNetworkVariables), reportNetworkVariables);
    encoder.Encode(to_underlying(Fields::kReportMoreNetworkVariables), reportMoreNetworkVariables);
    encoder.Encode(to_underlying(Fields::kReportWatermarkPercent), reportWatermarkPercent);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        VerifyOrReturnError(err != CHIP_ERROR_END_OF_TLV, CHIP_NO_ERROR);
        ReturnErrorOnFailure(err);

        if (__context_tag == to_underlying(Fields::kCoreDumpEnabled))
        {
            err = DataModel::Decode(reader, coreDumpEnabled);
        }
        else if (__context_tag == to_underlying(Fields::kMinInterval))
        {
            err = DataModel::Decode(reader, minInterval);
        }
        else if (__context_tag == to_underlying(Fields::kMaxInterval))
        {
            err = DataModel::Decode(reader, maxInterval);
        }
        else if (__context_tag == to_underlying(Fields::kDropWifiLogs))
        {
            err = DataModel::Decode(reader, dropWifiLogs);
        }
        else if (__context_tag == to_underlying(Fields::kReportMetrics))
        {
            err = DataModel::Decode(reader, reportMetrics);
        }
        else if (__context_tag == to_underlying(Fields::kReportHeapMetrics))
        {
            err = DataModel::Decode(reader, reportHeapMetrics);
        }
        else if (__context_tag == to_underlying(Fields::kHeapPollingInterval))
        {
            err = DataModel::Decode(reader, heapPollingInterval);
        }
        else if (__context_tag == to_underlying(Fields::kHeapPollingCount))
        {
            err = DataModel::Decode(reader, heapPollingCount);
        }
        else if (__context_tag == to_underlying(Fields::kReportWifiMetrics))
        {
            err = DataModel::Decode(reader, reportWifiMetrics);
        }
        else if (__context_tag == to_underlying(Fields::kWifiPollingInterval))
        {
            err = DataModel::Decode(reader, wifiPollingInterval);
        }
        else if (__context_tag == to_underlying(Fields::kWifiPollingCount))
        {
            err = DataModel::Decode(reader, wifiPollingCount);
        }
        else if (__context_tag == to_underlying(Fields::kUsePolling))
        {
            err = DataModel::Decode(reader, usePolling);
        }
        else if (__context_tag == to_underlying(Fields::kReportVariables))
        {
            err = DataModel::Decode(reader, reportVariables);
        }
        else if (__context_tag == to_underlying(Fields::kReportNetworkVariables))
        {
            err = DataModel::Decode(reader, reportNetworkVariables);
        }
        else if (__context_tag == to_underlying(Fields::kReportMoreNetworkVariables))
        {
            err = DataModel::Decode(reader, reportMoreNetworkVariables);
        }
        else if (__context_tag == to_underlying(Fields::kReportWatermarkPercent))
        {
            err = DataModel::Decode(reader, reportWatermarkPercent);
        }

        ReturnErrorOnFailure(err);
    }
}

} // namespace PhotonInsightsParamsStruct

namespace PhotonMQTTStruct {
CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kHost), host);
    encoder.Encode(to_underlying(Fields::kPort), port);
    encoder.Encode(to_underlying(Fields::kTransport), transport);
    encoder.Encode(to_underlying(Fields::kKeepAlive), keepAlive);
    encoder.Encode(to_underlying(Fields::kCleanSession), cleanSession);
    encoder.Encode(to_underlying(Fields::kReconnectTimeoutMS), reconnectTimeoutMS);
    encoder.Encode(to_underlying(Fields::kTimeoutMS), timeoutMS);
    encoder.Encode(to_underlying(Fields::kRefreshConnectionAfterMS), refreshConnectionAfterMS);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        VerifyOrReturnError(err != CHIP_ERROR_END_OF_TLV, CHIP_NO_ERROR);
        ReturnErrorOnFailure(err);

        if (__context_tag == to_underlying(Fields::kHost))
        {
            err = DataModel::Decode(reader, host);
        }
        else if (__context_tag == to_underlying(Fields::kPort))
        {
            err = DataModel::Decode(reader, port);
        }
        else if (__context_tag == to_underlying(Fields::kTransport))
        {
            err = DataModel::Decode(reader, transport);
        }
        else if (__context_tag == to_underlying(Fields::kKeepAlive))
        {
            err = DataModel::Decode(reader, keepAlive);
        }
        else if (__context_tag == to_underlying(Fields::kCleanSession))
        {
            err = DataModel::Decode(reader, cleanSession);
        }
        else if (__context_tag == to_underlying(Fields::kReconnectTimeoutMS))
        {
            err = DataModel::Decode(reader, reconnectTimeoutMS);
        }
        else if (__context_tag == to_underlying(Fields::kTimeoutMS))
        {
            err = DataModel::Decode(reader, timeoutMS);
        }
        else if (__context_tag == to_underlying(Fields::kRefreshConnectionAfterMS))
        {
            err = DataModel::Decode(reader, refreshConnectionAfterMS);
        }

        ReturnErrorOnFailure(err);
    }
}

} // namespace PhotonMQTTStruct
} // namespace Structs
} // namespace PhotonSmart
} // namespace Clusters
} // namespace app
} // namespace chip
