/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Structs.ipp.zapt

#include <clusters/PhotonSmart/Structs.h>

#include <app/data-model/StructDecodeIterator.h>
#include <app/data-model/WrappedStructEncoder.h>

namespace chip {
namespace app {
namespace Clusters {
namespace PhotonSmart {
namespace Structs {

namespace PhotonMQTTStruct {
CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kHost), host);
    encoder.Encode(to_underlying(Fields::kPort), port);
    encoder.Encode(to_underlying(Fields::kTransport), transport);
    encoder.Encode(to_underlying(Fields::kKeepAlive), keepAlive);
    encoder.Encode(to_underlying(Fields::kLastWellTopic), lastWellTopic);
    encoder.Encode(to_underlying(Fields::kLastWellMsg), lastWellMsg);
    encoder.Encode(to_underlying(Fields::kLastWellMsgLen), lastWellMsgLen);
    encoder.Encode(to_underlying(Fields::kLastWellQOS), lastWellQOS);
    encoder.Encode(to_underlying(Fields::kLastWellRetain), lastWellRetain);
    encoder.Encode(to_underlying(Fields::kCleanSession), cleanSession);
    encoder.Encode(to_underlying(Fields::kReconnectTimeoutMS), reconnectTimeoutMS);
    encoder.Encode(to_underlying(Fields::kTimeoutMS), timeoutMS);
    encoder.Encode(to_underlying(Fields::kRefreshConnectionAfterMS), refreshConnectionAfterMS);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        VerifyOrReturnError(err != CHIP_ERROR_END_OF_TLV, CHIP_NO_ERROR);
        ReturnErrorOnFailure(err);

        if (__context_tag == to_underlying(Fields::kHost))
        {
            err = DataModel::Decode(reader, host);
        }
        else if (__context_tag == to_underlying(Fields::kPort))
        {
            err = DataModel::Decode(reader, port);
        }
        else if (__context_tag == to_underlying(Fields::kTransport))
        {
            err = DataModel::Decode(reader, transport);
        }
        else if (__context_tag == to_underlying(Fields::kKeepAlive))
        {
            err = DataModel::Decode(reader, keepAlive);
        }
        else if (__context_tag == to_underlying(Fields::kLastWellTopic))
        {
            err = DataModel::Decode(reader, lastWellTopic);
        }
        else if (__context_tag == to_underlying(Fields::kLastWellMsg))
        {
            err = DataModel::Decode(reader, lastWellMsg);
        }
        else if (__context_tag == to_underlying(Fields::kLastWellMsgLen))
        {
            err = DataModel::Decode(reader, lastWellMsgLen);
        }
        else if (__context_tag == to_underlying(Fields::kLastWellQOS))
        {
            err = DataModel::Decode(reader, lastWellQOS);
        }
        else if (__context_tag == to_underlying(Fields::kLastWellRetain))
        {
            err = DataModel::Decode(reader, lastWellRetain);
        }
        else if (__context_tag == to_underlying(Fields::kCleanSession))
        {
            err = DataModel::Decode(reader, cleanSession);
        }
        else if (__context_tag == to_underlying(Fields::kReconnectTimeoutMS))
        {
            err = DataModel::Decode(reader, reconnectTimeoutMS);
        }
        else if (__context_tag == to_underlying(Fields::kTimeoutMS))
        {
            err = DataModel::Decode(reader, timeoutMS);
        }
        else if (__context_tag == to_underlying(Fields::kRefreshConnectionAfterMS))
        {
            err = DataModel::Decode(reader, refreshConnectionAfterMS);
        }

        ReturnErrorOnFailure(err);
    }
}

} // namespace PhotonMQTTStruct
} // namespace Structs
} // namespace PhotonSmart
} // namespace Clusters
} // namespace app
} // namespace chip
