/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Structs.h.zapt

#pragma once

#include <app/data-model/DecodableList.h>
#include <app/data-model/List.h>
#include <app/data-model/Nullable.h>
#include <lib/core/DataModelTypes.h>
#include <lib/core/Optional.h>
#include <lib/core/TLV.h>
#include <lib/support/BitMask.h>

#include <clusters/shared/Structs.h>

#include <cstdint>

namespace chip {
namespace app {
namespace Clusters {
namespace PhotonSmart {
namespace Structs {
namespace PhotonMQTTStruct {
enum class Fields : uint8_t
{
    kHost                     = 1,
    kPort                     = 2,
    kTransport                = 3,
    kKeepAlive                = 4,
    kLastWellTopic            = 5,
    kLastWellMsg              = 6,
    kLastWellMsgLen           = 7,
    kLastWellQOS              = 8,
    kLastWellRetain           = 9,
    kCleanSession             = 10,
    kReconnectTimeoutMS       = 11,
    kTimeoutMS                = 12,
    kRefreshConnectionAfterMS = 13,
};

struct Type
{
public:
    chip::CharSpan host;
    uint16_t port           = static_cast<uint16_t>(0);
    MqttTransport transport = static_cast<MqttTransport>(0);
    uint16_t keepAlive      = static_cast<uint16_t>(0);
    chip::CharSpan lastWellTopic;
    chip::ByteSpan lastWellMsg;
    uint16_t lastWellMsgLen           = static_cast<uint16_t>(0);
    uint8_t lastWellQOS               = static_cast<uint8_t>(0);
    bool lastWellRetain               = static_cast<bool>(0);
    bool cleanSession                 = static_cast<bool>(0);
    uint32_t reconnectTimeoutMS       = static_cast<uint32_t>(0);
    uint32_t timeoutMS                = static_cast<uint32_t>(0);
    uint32_t refreshConnectionAfterMS = static_cast<uint32_t>(0);

    CHIP_ERROR Decode(TLV::TLVReader & reader);

    static constexpr bool kIsFabricScoped = false;

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;
};

using DecodableType = Type;

} // namespace PhotonMQTTStruct
} // namespace Structs
} // namespace PhotonSmart
} // namespace Clusters
} // namespace app
} // namespace chip
