/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Structs.h.zapt

#pragma once

#include <app/data-model/DecodableList.h>
#include <app/data-model/List.h>
#include <app/data-model/Nullable.h>
#include <lib/core/DataModelTypes.h>
#include <lib/core/Optional.h>
#include <lib/core/TLV.h>
#include <lib/support/BitMask.h>

#include <clusters/shared/Structs.h>

#include <cstdint>

namespace chip {
namespace app {
namespace Clusters {
namespace PhotonSmart {
namespace Structs {
namespace PhotonInsightsParamsStruct {
enum class Fields : uint8_t
{
    kCoreDumpEnabled            = 0,
    kMinInterval                = 1,
    kMaxInterval                = 2,
    kDropWifiLogs               = 3,
    kReportMetrics              = 4,
    kReportHeapMetrics          = 5,
    kHeapPollingInterval        = 6,
    kHeapPollingCount           = 7,
    kReportWifiMetrics          = 8,
    kWifiPollingInterval        = 9,
    kWifiPollingCount           = 10,
    kUsePolling                 = 11,
    kReportVariables            = 12,
    kReportNetworkVariables     = 13,
    kReportMoreNetworkVariables = 14,
    kReportWatermarkPercent     = 15,
};

struct Type
{
public:
    bool coreDumpEnabled                 = static_cast<bool>(0);
    uint32_t minInterval                 = static_cast<uint32_t>(0);
    uint32_t maxInterval                 = static_cast<uint32_t>(0);
    bool dropWifiLogs                    = static_cast<bool>(0);
    bool reportMetrics                   = static_cast<bool>(0);
    bool reportHeapMetrics               = static_cast<bool>(0);
    uint32_t heapPollingInterval         = static_cast<uint32_t>(0);
    uint8_t heapPollingCount             = static_cast<uint8_t>(0);
    bool reportWifiMetrics               = static_cast<bool>(0);
    uint32_t wifiPollingInterval         = static_cast<uint32_t>(0);
    uint8_t wifiPollingCount             = static_cast<uint8_t>(0);
    bool usePolling                      = static_cast<bool>(0);
    bool reportVariables                 = static_cast<bool>(0);
    bool reportNetworkVariables          = static_cast<bool>(0);
    bool reportMoreNetworkVariables      = static_cast<bool>(0);
    chip::Percent reportWatermarkPercent = static_cast<chip::Percent>(0);

    CHIP_ERROR Decode(TLV::TLVReader & reader);

    static constexpr bool kIsFabricScoped = false;

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;
};

using DecodableType = Type;

} // namespace PhotonInsightsParamsStruct
namespace PhotonMQTTStruct {
enum class Fields : uint8_t
{
    kHost                     = 1,
    kPort                     = 2,
    kTransport                = 3,
    kKeepAlive                = 4,
    kCleanSession             = 5,
    kReconnectTimeoutMS       = 6,
    kTimeoutMS                = 7,
    kRefreshConnectionAfterMS = 8,
};

struct Type
{
public:
    chip::CharSpan host;
    uint16_t port                     = static_cast<uint16_t>(0);
    MqttTransport transport           = static_cast<MqttTransport>(0);
    uint16_t keepAlive                = static_cast<uint16_t>(0);
    bool cleanSession                 = static_cast<bool>(0);
    uint32_t reconnectTimeoutMS       = static_cast<uint32_t>(0);
    uint32_t timeoutMS                = static_cast<uint32_t>(0);
    uint32_t refreshConnectionAfterMS = static_cast<uint32_t>(0);

    CHIP_ERROR Decode(TLV::TLVReader & reader);

    static constexpr bool kIsFabricScoped = false;

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;
};

using DecodableType = Type;

} // namespace PhotonMQTTStruct
} // namespace Structs
} // namespace PhotonSmart
} // namespace Clusters
} // namespace app
} // namespace chip
