/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Attributes.ipp.zapt

#include <clusters/FreshWaterHeaterController/Attributes.h>

#include <app/data-model/Decode.h>
#include <app/data-model/WrappedStructEncoder.h>

namespace chip {
namespace app {
namespace Clusters {
namespace FreshWaterHeaterController {
namespace Attributes {
CHIP_ERROR TypeInfo::DecodableType::Decode(TLV::TLVReader & reader, const ConcreteAttributePath & path)
{
    switch (path.mAttributeId)
    {
    case Attributes::ColdWaterTemperature::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, coldWaterTemperature);
    case Attributes::ShowerTemperature::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, showerTemperature);
    case Attributes::ShowerHysteresis::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, showerHysteresis);
    case Attributes::ShowerState::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, showerState);
    case Attributes::DefaultShowerFlowLPM::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, defaultShowerFlowLPM);
    case Attributes::StandardModeSetpoint::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, standardModeSetpoint);
    case Attributes::EcoModeSetpoint::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, ecoModeSetpoint);
    case Attributes::BoostModeSetpoint::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, boostModeSetpoint);
    case Attributes::DisplayTemperatureStep::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, displayTemperatureStep);
    case Attributes::ResetTimeout::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, resetTimeout);
    case Attributes::CoolDownTimeout::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, coolDownTimeout);
    case Attributes::ResetCounterTimeout::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, resetCounterTimeout);
    case Attributes::DisplayActiveTimeout::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, displayActiveTimeout);
    case Attributes::DisplayErrorTimeout::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, displayErrorTimeout);
    case Attributes::DisplayTargetTimeout::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, displayTargetTimeout);
    case Attributes::TemperatureSensorMinValid::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, temperatureSensorMinValid);
    case Attributes::TemperatureSensorMaxValid::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, temperatureSensorMaxValid);
    case Attributes::OverheatThresholdTemperature::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, overheatThresholdTemperature);
    case Attributes::RapidRiseDelta::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, rapidRiseDelta);
    case Attributes::RapidRiseWindow::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, rapidRiseWindow);
    case Attributes::PreviousTargetHeaterTemperature::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, previousTargetHeaterTemperature);
    case Attributes::HeaterMaximumPower::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, heaterMaximumPower);
    case Attributes::DiagnosticsConfirmTimeList::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, diagnosticsConfirmTimeList);
    case Attributes::DiagnosticsRehabTimeList::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, diagnosticsRehabTimeList);
    case Attributes::GeneratedCommandList::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, generatedCommandList);
    case Attributes::AcceptedCommandList::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, acceptedCommandList);
    case Attributes::AttributeList::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, attributeList);
    case Attributes::FeatureMap::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, featureMap);
    case Attributes::ClusterRevision::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, clusterRevision);
    default:
        return CHIP_NO_ERROR;
    }
}
} // namespace Attributes
} // namespace FreshWaterHeaterController
} // namespace Clusters
} // namespace app
} // namespace chip
