/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Attributes.h.zapt

#pragma once

#include <app/ConcreteAttributePath.h>
#include <app/data-model/DecodableList.h>
#include <app/data-model/List.h>
#include <app/data-model/Nullable.h>
#include <app/util/basic-types.h>
#include <lib/core/TLV.h>
#include <lib/support/BitMask.h>

#include <clusters/shared/Attributes.h>
#include <clusters/shared/Enums.h>
#include <clusters/shared/Structs.h>

#include <clusters/FreshWaterHeaterController/AttributeIds.h>
#include <clusters/FreshWaterHeaterController/ClusterId.h>
#include <clusters/FreshWaterHeaterController/Enums.h>
#include <clusters/FreshWaterHeaterController/Structs.h>

namespace chip {
namespace app {
namespace Clusters {
namespace FreshWaterHeaterController {
namespace Attributes {

namespace ColdWaterTemperature {
struct TypeInfo
{
    using Type             = int16_t;
    using DecodableType    = int16_t;
    using DecodableArgType = int16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::ColdWaterTemperature::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace ColdWaterTemperature
namespace ShowerTemperature {
struct TypeInfo
{
    using Type             = int16_t;
    using DecodableType    = int16_t;
    using DecodableArgType = int16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::ShowerTemperature::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace ShowerTemperature
namespace ShowerHysteresis {
struct TypeInfo
{
    using Type             = int16_t;
    using DecodableType    = int16_t;
    using DecodableArgType = int16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::ShowerHysteresis::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace ShowerHysteresis
namespace ShowerState {
struct TypeInfo
{
    using Type             = chip::app::Clusters::FreshWaterHeaterController::ShowerStateEnum;
    using DecodableType    = chip::app::Clusters::FreshWaterHeaterController::ShowerStateEnum;
    using DecodableArgType = chip::app::Clusters::FreshWaterHeaterController::ShowerStateEnum;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::ShowerState::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace ShowerState
namespace DefaultShowerFlowLPM {
struct TypeInfo
{
    using Type             = uint16_t;
    using DecodableType    = uint16_t;
    using DecodableArgType = uint16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::DefaultShowerFlowLPM::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace DefaultShowerFlowLPM
namespace StandardModeSetpoint {
struct TypeInfo
{
    using Type             = int16_t;
    using DecodableType    = int16_t;
    using DecodableArgType = int16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::StandardModeSetpoint::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace StandardModeSetpoint
namespace EcoModeSetpoint {
struct TypeInfo
{
    using Type             = int16_t;
    using DecodableType    = int16_t;
    using DecodableArgType = int16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::EcoModeSetpoint::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace EcoModeSetpoint
namespace BoostModeSetpoint {
struct TypeInfo
{
    using Type          = chip::app::Clusters::FreshWaterHeaterController::Structs::WaterHeaterBoostInfoStruct::Type;
    using DecodableType = chip::app::Clusters::FreshWaterHeaterController::Structs::WaterHeaterBoostInfoStruct::DecodableType;
    using DecodableArgType =
        const chip::app::Clusters::FreshWaterHeaterController::Structs::WaterHeaterBoostInfoStruct::DecodableType &;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::BoostModeSetpoint::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace BoostModeSetpoint
namespace DisplayTemperatureStep {
struct TypeInfo
{
    using Type             = int16_t;
    using DecodableType    = int16_t;
    using DecodableArgType = int16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::DisplayTemperatureStep::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace DisplayTemperatureStep
namespace ResetTimeout {
struct TypeInfo
{
    using Type             = uint32_t;
    using DecodableType    = uint32_t;
    using DecodableArgType = uint32_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::ResetTimeout::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace ResetTimeout
namespace CoolDownTimeout {
struct TypeInfo
{
    using Type             = uint32_t;
    using DecodableType    = uint32_t;
    using DecodableArgType = uint32_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::CoolDownTimeout::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace CoolDownTimeout
namespace ResetCounterTimeout {
struct TypeInfo
{
    using Type             = uint32_t;
    using DecodableType    = uint32_t;
    using DecodableArgType = uint32_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::ResetCounterTimeout::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace ResetCounterTimeout
namespace DisplayActiveTimeout {
struct TypeInfo
{
    using Type             = uint32_t;
    using DecodableType    = uint32_t;
    using DecodableArgType = uint32_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::DisplayActiveTimeout::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace DisplayActiveTimeout
namespace DisplayErrorTimeout {
struct TypeInfo
{
    using Type             = uint32_t;
    using DecodableType    = uint32_t;
    using DecodableArgType = uint32_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::DisplayErrorTimeout::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace DisplayErrorTimeout
namespace DisplayTargetTimeout {
struct TypeInfo
{
    using Type             = uint32_t;
    using DecodableType    = uint32_t;
    using DecodableArgType = uint32_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::DisplayTargetTimeout::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace DisplayTargetTimeout
namespace TemperatureSensorMinValid {
struct TypeInfo
{
    using Type             = int16_t;
    using DecodableType    = int16_t;
    using DecodableArgType = int16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::TemperatureSensorMinValid::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace TemperatureSensorMinValid
namespace TemperatureSensorMaxValid {
struct TypeInfo
{
    using Type             = int16_t;
    using DecodableType    = int16_t;
    using DecodableArgType = int16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::TemperatureSensorMaxValid::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace TemperatureSensorMaxValid
namespace OverheatThresholdTemperature {
struct TypeInfo
{
    using Type             = int16_t;
    using DecodableType    = int16_t;
    using DecodableArgType = int16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::OverheatThresholdTemperature::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace OverheatThresholdTemperature
namespace RapidRiseDelta {
struct TypeInfo
{
    using Type             = int16_t;
    using DecodableType    = int16_t;
    using DecodableArgType = int16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::RapidRiseDelta::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace RapidRiseDelta
namespace RapidRiseWindow {
struct TypeInfo
{
    using Type             = uint32_t;
    using DecodableType    = uint32_t;
    using DecodableArgType = uint32_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::RapidRiseWindow::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace RapidRiseWindow
namespace PreviousTargetHeaterTemperature {
struct TypeInfo
{
    using Type             = int16_t;
    using DecodableType    = int16_t;
    using DecodableArgType = int16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::PreviousTargetHeaterTemperature::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace PreviousTargetHeaterTemperature
namespace HeaterMaximumPower {
struct TypeInfo
{
    using Type             = uint16_t;
    using DecodableType    = uint16_t;
    using DecodableArgType = uint16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::HeaterMaximumPower::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace HeaterMaximumPower
namespace DiagnosticsConfirmTimeList {
struct TypeInfo
{
    using Type             = chip::app::DataModel::List<const uint32_t>;
    using DecodableType    = chip::app::DataModel::DecodableList<uint32_t>;
    using DecodableArgType = const chip::app::DataModel::DecodableList<uint32_t> &;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::DiagnosticsConfirmTimeList::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace DiagnosticsConfirmTimeList
namespace DiagnosticsRehabTimeList {
struct TypeInfo
{
    using Type             = chip::app::DataModel::List<const uint32_t>;
    using DecodableType    = chip::app::DataModel::DecodableList<uint32_t>;
    using DecodableArgType = const chip::app::DataModel::DecodableList<uint32_t> &;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::DiagnosticsRehabTimeList::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace DiagnosticsRehabTimeList
namespace RequiresAnodeChange {
struct TypeInfo
{
    using Type             = bool;
    using DecodableType    = bool;
    using DecodableArgType = bool;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::RequiresAnodeChange::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace RequiresAnodeChange
namespace MaximumBoostTime {
struct TypeInfo
{
    using Type             = uint32_t;
    using DecodableType    = uint32_t;
    using DecodableArgType = uint32_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::MaximumBoostTime::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace MaximumBoostTime
namespace GeneratedCommandList {
struct TypeInfo : public Clusters::Globals::Attributes::GeneratedCommandList::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
};
} // namespace GeneratedCommandList
namespace AcceptedCommandList {
struct TypeInfo : public Clusters::Globals::Attributes::AcceptedCommandList::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
};
} // namespace AcceptedCommandList
namespace AttributeList {
struct TypeInfo : public Clusters::Globals::Attributes::AttributeList::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
};
} // namespace AttributeList
namespace FeatureMap {
struct TypeInfo : public Clusters::Globals::Attributes::FeatureMap::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
};
} // namespace FeatureMap
namespace ClusterRevision {
struct TypeInfo : public Clusters::Globals::Attributes::ClusterRevision::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }
};
} // namespace ClusterRevision

struct TypeInfo
{
    struct DecodableType
    {
        static constexpr ClusterId GetClusterId() { return Clusters::FreshWaterHeaterController::Id; }

        CHIP_ERROR Decode(TLV::TLVReader & reader, const ConcreteAttributePath & path);

        Attributes::ColdWaterTemperature::TypeInfo::DecodableType coldWaterTemperature = static_cast<int16_t>(0);
        Attributes::ShowerTemperature::TypeInfo::DecodableType showerTemperature       = static_cast<int16_t>(0);
        Attributes::ShowerHysteresis::TypeInfo::DecodableType showerHysteresis         = static_cast<int16_t>(0);
        Attributes::ShowerState::TypeInfo::DecodableType showerState =
            static_cast<chip::app::Clusters::FreshWaterHeaterController::ShowerStateEnum>(0);
        Attributes::DefaultShowerFlowLPM::TypeInfo::DecodableType defaultShowerFlowLPM = static_cast<uint16_t>(0);
        Attributes::StandardModeSetpoint::TypeInfo::DecodableType standardModeSetpoint = static_cast<int16_t>(0);
        Attributes::EcoModeSetpoint::TypeInfo::DecodableType ecoModeSetpoint           = static_cast<int16_t>(0);
        Attributes::BoostModeSetpoint::TypeInfo::DecodableType boostModeSetpoint;
        Attributes::DisplayTemperatureStep::TypeInfo::DecodableType displayTemperatureStep             = static_cast<int16_t>(0);
        Attributes::ResetTimeout::TypeInfo::DecodableType resetTimeout                                 = static_cast<uint32_t>(0);
        Attributes::CoolDownTimeout::TypeInfo::DecodableType coolDownTimeout                           = static_cast<uint32_t>(0);
        Attributes::ResetCounterTimeout::TypeInfo::DecodableType resetCounterTimeout                   = static_cast<uint32_t>(0);
        Attributes::DisplayActiveTimeout::TypeInfo::DecodableType displayActiveTimeout                 = static_cast<uint32_t>(0);
        Attributes::DisplayErrorTimeout::TypeInfo::DecodableType displayErrorTimeout                   = static_cast<uint32_t>(0);
        Attributes::DisplayTargetTimeout::TypeInfo::DecodableType displayTargetTimeout                 = static_cast<uint32_t>(0);
        Attributes::TemperatureSensorMinValid::TypeInfo::DecodableType temperatureSensorMinValid       = static_cast<int16_t>(0);
        Attributes::TemperatureSensorMaxValid::TypeInfo::DecodableType temperatureSensorMaxValid       = static_cast<int16_t>(0);
        Attributes::OverheatThresholdTemperature::TypeInfo::DecodableType overheatThresholdTemperature = static_cast<int16_t>(0);
        Attributes::RapidRiseDelta::TypeInfo::DecodableType rapidRiseDelta                             = static_cast<int16_t>(0);
        Attributes::RapidRiseWindow::TypeInfo::DecodableType rapidRiseWindow                           = static_cast<uint32_t>(0);
        Attributes::PreviousTargetHeaterTemperature::TypeInfo::DecodableType previousTargetHeaterTemperature =
            static_cast<int16_t>(0);
        Attributes::HeaterMaximumPower::TypeInfo::DecodableType heaterMaximumPower = static_cast<uint16_t>(0);
        Attributes::DiagnosticsConfirmTimeList::TypeInfo::DecodableType diagnosticsConfirmTimeList;
        Attributes::DiagnosticsRehabTimeList::TypeInfo::DecodableType diagnosticsRehabTimeList;
        Attributes::RequiresAnodeChange::TypeInfo::DecodableType requiresAnodeChange = static_cast<bool>(0);
        Attributes::MaximumBoostTime::TypeInfo::DecodableType maximumBoostTime       = static_cast<uint32_t>(0);
        Attributes::GeneratedCommandList::TypeInfo::DecodableType generatedCommandList;
        Attributes::AcceptedCommandList::TypeInfo::DecodableType acceptedCommandList;
        Attributes::AttributeList::TypeInfo::DecodableType attributeList;
        Attributes::FeatureMap::TypeInfo::DecodableType featureMap           = static_cast<uint32_t>(0);
        Attributes::ClusterRevision::TypeInfo::DecodableType clusterRevision = static_cast<uint16_t>(0);
    };
};
} // namespace Attributes
} // namespace FreshWaterHeaterController
} // namespace Clusters
} // namespace app
} // namespace chip
