/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Attributes.ipp.zapt

#include <clusters/FreshMideaController/Attributes.h>

#include <app/data-model/Decode.h>
#include <app/data-model/WrappedStructEncoder.h>

namespace chip {
namespace app {
namespace Clusters {
namespace FreshMideaController {
namespace Attributes {
CHIP_ERROR TypeInfo::DecodableType::Decode(TLV::TLVReader & reader, const ConcreteAttributePath & path)
{
    switch (path.mAttributeId)
    {
    case Attributes::Beep::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, beep);
    case Attributes::Light::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, light);
    case Attributes::TurboMode::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, turboMode);
    case Attributes::EcoMode::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, ecoMode);
    case Attributes::FrostProtectionMode::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, frostProtectionMode);
    case Attributes::SleepMode::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, sleepMode);
    case Attributes::TemperatureUnit::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, temperatureUnit);
    case Attributes::CleanState::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, cleanState);
    case Attributes::OffTimer::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, offTimer);
    case Attributes::OffTimerHours::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, offTimerHours);
    case Attributes::OffTimerMinutes::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, offTimerMinutes);
    case Attributes::OnTimer::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, onTimer);
    case Attributes::OnTimerHours::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, onTimerHours);
    case Attributes::OnTimerMinutes::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, onTimerMinutes);
    case Attributes::PlasmaMode::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, plasmaMode);
    case Attributes::BreezeAwayMode::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, breezeAwayMode);
    case Attributes::ErrorCode::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, errorCode);
    case Attributes::HorizontalLouverPosition::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, horizontalLouverPosition);
    case Attributes::GeneratedCommandList::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, generatedCommandList);
    case Attributes::AcceptedCommandList::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, acceptedCommandList);
    case Attributes::AttributeList::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, attributeList);
    case Attributes::FeatureMap::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, featureMap);
    case Attributes::ClusterRevision::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, clusterRevision);
    default:
        return CHIP_NO_ERROR;
    }
}
} // namespace Attributes
} // namespace FreshMideaController
} // namespace Clusters
} // namespace app
} // namespace chip
