/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Attributes.h.zapt

#pragma once

#include <app/ConcreteAttributePath.h>
#include <app/data-model/DecodableList.h>
#include <app/data-model/List.h>
#include <app/data-model/Nullable.h>
#include <app/util/basic-types.h>
#include <lib/core/TLV.h>
#include <lib/support/BitMask.h>

#include <clusters/shared/Attributes.h>
#include <clusters/shared/Enums.h>
#include <clusters/shared/Structs.h>

#include <clusters/FreshMideaController/AttributeIds.h>
#include <clusters/FreshMideaController/ClusterId.h>
#include <clusters/FreshMideaController/Enums.h>
#include <clusters/FreshMideaController/Structs.h>

namespace chip {
namespace app {
namespace Clusters {
namespace FreshMideaController {
namespace Attributes {

namespace Beep {
struct TypeInfo
{
    using Type             = bool;
    using DecodableType    = bool;
    using DecodableArgType = bool;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::Beep::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace Beep
namespace Light {
struct TypeInfo
{
    using Type             = bool;
    using DecodableType    = bool;
    using DecodableArgType = bool;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::Light::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace Light
namespace TurboMode {
struct TypeInfo
{
    using Type             = bool;
    using DecodableType    = bool;
    using DecodableArgType = bool;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::TurboMode::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace TurboMode
namespace EcoMode {
struct TypeInfo
{
    using Type             = bool;
    using DecodableType    = bool;
    using DecodableArgType = bool;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::EcoMode::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace EcoMode
namespace FrostProtectionMode {
struct TypeInfo
{
    using Type             = bool;
    using DecodableType    = bool;
    using DecodableArgType = bool;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::FrostProtectionMode::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace FrostProtectionMode
namespace SleepMode {
struct TypeInfo
{
    using Type             = bool;
    using DecodableType    = bool;
    using DecodableArgType = bool;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::SleepMode::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace SleepMode
namespace TemperatureUnit {
struct TypeInfo
{
    using Type             = chip::app::Clusters::FreshMideaController::TemperatureUnitsEnum;
    using DecodableType    = chip::app::Clusters::FreshMideaController::TemperatureUnitsEnum;
    using DecodableArgType = chip::app::Clusters::FreshMideaController::TemperatureUnitsEnum;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::TemperatureUnit::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace TemperatureUnit
namespace CleanState {
struct TypeInfo
{
    using Type             = chip::app::Clusters::FreshMideaController::CleanStateEnum;
    using DecodableType    = chip::app::Clusters::FreshMideaController::CleanStateEnum;
    using DecodableArgType = chip::app::Clusters::FreshMideaController::CleanStateEnum;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::CleanState::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace CleanState
namespace OffTimer {
struct TypeInfo
{
    using Type             = bool;
    using DecodableType    = bool;
    using DecodableArgType = bool;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::OffTimer::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace OffTimer
namespace OffTimerHours {
struct TypeInfo
{
    using Type             = uint8_t;
    using DecodableType    = uint8_t;
    using DecodableArgType = uint8_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::OffTimerHours::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace OffTimerHours
namespace OffTimerMinutes {
struct TypeInfo
{
    using Type             = uint8_t;
    using DecodableType    = uint8_t;
    using DecodableArgType = uint8_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::OffTimerMinutes::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace OffTimerMinutes
namespace OnTimer {
struct TypeInfo
{
    using Type             = bool;
    using DecodableType    = bool;
    using DecodableArgType = bool;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::OnTimer::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace OnTimer
namespace OnTimerHours {
struct TypeInfo
{
    using Type             = uint8_t;
    using DecodableType    = uint8_t;
    using DecodableArgType = uint8_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::OnTimerHours::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace OnTimerHours
namespace OnTimerMinutes {
struct TypeInfo
{
    using Type             = uint8_t;
    using DecodableType    = uint8_t;
    using DecodableArgType = uint8_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::OnTimerMinutes::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace OnTimerMinutes
namespace PlasmaMode {
struct TypeInfo
{
    using Type             = bool;
    using DecodableType    = bool;
    using DecodableArgType = bool;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::PlasmaMode::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace PlasmaMode
namespace ErrorCode {
struct TypeInfo
{
    using Type             = uint16_t;
    using DecodableType    = uint16_t;
    using DecodableArgType = uint16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::ErrorCode::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace ErrorCode
namespace GeneratedCommandList {
struct TypeInfo : public Clusters::Globals::Attributes::GeneratedCommandList::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
};
} // namespace GeneratedCommandList
namespace AcceptedCommandList {
struct TypeInfo : public Clusters::Globals::Attributes::AcceptedCommandList::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
};
} // namespace AcceptedCommandList
namespace AttributeList {
struct TypeInfo : public Clusters::Globals::Attributes::AttributeList::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
};
} // namespace AttributeList
namespace FeatureMap {
struct TypeInfo : public Clusters::Globals::Attributes::FeatureMap::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
};
} // namespace FeatureMap
namespace ClusterRevision {
struct TypeInfo : public Clusters::Globals::Attributes::ClusterRevision::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
};
} // namespace ClusterRevision

struct TypeInfo
{
    struct DecodableType
    {
        static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }

        CHIP_ERROR Decode(TLV::TLVReader & reader, const ConcreteAttributePath & path);

        Attributes::Beep::TypeInfo::DecodableType beep                               = static_cast<bool>(0);
        Attributes::Light::TypeInfo::DecodableType light                             = static_cast<bool>(0);
        Attributes::TurboMode::TypeInfo::DecodableType turboMode                     = static_cast<bool>(0);
        Attributes::EcoMode::TypeInfo::DecodableType ecoMode                         = static_cast<bool>(0);
        Attributes::FrostProtectionMode::TypeInfo::DecodableType frostProtectionMode = static_cast<bool>(0);
        Attributes::SleepMode::TypeInfo::DecodableType sleepMode                     = static_cast<bool>(0);
        Attributes::TemperatureUnit::TypeInfo::DecodableType temperatureUnit =
            static_cast<chip::app::Clusters::FreshMideaController::TemperatureUnitsEnum>(0);
        Attributes::CleanState::TypeInfo::DecodableType cleanState =
            static_cast<chip::app::Clusters::FreshMideaController::CleanStateEnum>(0);
        Attributes::OffTimer::TypeInfo::DecodableType offTimer               = static_cast<bool>(0);
        Attributes::OffTimerHours::TypeInfo::DecodableType offTimerHours     = static_cast<uint8_t>(0);
        Attributes::OffTimerMinutes::TypeInfo::DecodableType offTimerMinutes = static_cast<uint8_t>(0);
        Attributes::OnTimer::TypeInfo::DecodableType onTimer                 = static_cast<bool>(0);
        Attributes::OnTimerHours::TypeInfo::DecodableType onTimerHours       = static_cast<uint8_t>(0);
        Attributes::OnTimerMinutes::TypeInfo::DecodableType onTimerMinutes   = static_cast<uint8_t>(0);
        Attributes::PlasmaMode::TypeInfo::DecodableType plasmaMode           = static_cast<bool>(0);
        Attributes::ErrorCode::TypeInfo::DecodableType errorCode             = static_cast<uint16_t>(0);
        Attributes::GeneratedCommandList::TypeInfo::DecodableType generatedCommandList;
        Attributes::AcceptedCommandList::TypeInfo::DecodableType acceptedCommandList;
        Attributes::AttributeList::TypeInfo::DecodableType attributeList;
        Attributes::FeatureMap::TypeInfo::DecodableType featureMap           = static_cast<uint32_t>(0);
        Attributes::ClusterRevision::TypeInfo::DecodableType clusterRevision = static_cast<uint16_t>(0);
    };
};
} // namespace Attributes
} // namespace FreshMideaController
} // namespace Clusters
} // namespace app
} // namespace chip
