/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Commands.h.zapt

#pragma once

#include <app/data-model/DecodableList.h>
#include <app/data-model/Encode.h>
#include <app/data-model/List.h>
#include <app/data-model/NullObject.h>
#include <app/data-model/Nullable.h>
#include <lib/core/DataModelTypes.h>
#include <lib/core/Optional.h>
#include <lib/core/TLV.h>
#include <lib/support/BitMask.h>

#include <clusters/shared/Enums.h>
#include <clusters/shared/Structs.h>

#include <clusters/FreshMideaController/ClusterId.h>
#include <clusters/FreshMideaController/CommandIds.h>
#include <clusters/FreshMideaController/Enums.h>
#include <clusters/FreshMideaController/Structs.h>

#include <cstdint>

namespace chip {
namespace app {
namespace Clusters {
namespace FreshMideaController {
namespace Commands {
// Forward-declarations so we can reference these later.

namespace Clean {
struct Type;
struct DecodableType;
} // namespace Clean

namespace CancelClean {
struct Type;
struct DecodableType;
} // namespace CancelClean

namespace SetTimer {
struct Type;
struct DecodableType;
} // namespace SetTimer

namespace CancelTimer {
struct Type;
struct DecodableType;
} // namespace CancelTimer

} // namespace Commands

namespace Commands {
namespace Clean {
enum class Fields : uint8_t
{
};

struct Type
{
public:
    // Use GetCommandId instead of commandId directly to avoid naming conflict with CommandIdentification in ExecutionOfACommand
    static constexpr CommandId GetCommandId() { return Commands::Clean::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;

    using ResponseType = DataModel::NullObjectType;

    static constexpr bool MustUseTimedInvoke() { return false; }
};

struct DecodableType
{
public:
    static constexpr CommandId GetCommandId() { return Commands::Clean::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
    static constexpr bool kIsFabricScoped = false;

    CHIP_ERROR Decode(TLV::TLVReader & reader);
};
}; // namespace Clean
namespace CancelClean {
enum class Fields : uint8_t
{
};

struct Type
{
public:
    // Use GetCommandId instead of commandId directly to avoid naming conflict with CommandIdentification in ExecutionOfACommand
    static constexpr CommandId GetCommandId() { return Commands::CancelClean::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;

    using ResponseType = DataModel::NullObjectType;

    static constexpr bool MustUseTimedInvoke() { return false; }
};

struct DecodableType
{
public:
    static constexpr CommandId GetCommandId() { return Commands::CancelClean::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
    static constexpr bool kIsFabricScoped = false;

    CHIP_ERROR Decode(TLV::TLVReader & reader);
};
}; // namespace CancelClean
namespace SetTimer {
enum class Fields : uint8_t
{
    kMode    = 0,
    kMinutes = 1,
};

struct Type
{
public:
    // Use GetCommandId instead of commandId directly to avoid naming conflict with CommandIdentification in ExecutionOfACommand
    static constexpr CommandId GetCommandId() { return Commands::SetTimer::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }

    bool mode        = static_cast<bool>(0);
    uint16_t minutes = static_cast<uint16_t>(0);

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;

    using ResponseType = DataModel::NullObjectType;

    static constexpr bool MustUseTimedInvoke() { return false; }
};

struct DecodableType
{
public:
    static constexpr CommandId GetCommandId() { return Commands::SetTimer::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
    static constexpr bool kIsFabricScoped = false;

    bool mode        = static_cast<bool>(0);
    uint16_t minutes = static_cast<uint16_t>(0);

    CHIP_ERROR Decode(TLV::TLVReader & reader);
};
}; // namespace SetTimer
namespace CancelTimer {
enum class Fields : uint8_t
{
    kMode = 0,
};

struct Type
{
public:
    // Use GetCommandId instead of commandId directly to avoid naming conflict with CommandIdentification in ExecutionOfACommand
    static constexpr CommandId GetCommandId() { return Commands::CancelTimer::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }

    bool mode = static_cast<bool>(0);

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;

    using ResponseType = DataModel::NullObjectType;

    static constexpr bool MustUseTimedInvoke() { return false; }
};

struct DecodableType
{
public:
    static constexpr CommandId GetCommandId() { return Commands::CancelTimer::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::FreshMideaController::Id; }
    static constexpr bool kIsFabricScoped = false;

    bool mode = static_cast<bool>(0);

    CHIP_ERROR Decode(TLV::TLVReader & reader);
};
}; // namespace CancelTimer
} // namespace Commands
} // namespace FreshMideaController
} // namespace Clusters
} // namespace app
} // namespace chip
