/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Attributes.h.zapt

#pragma once

#include <app/ConcreteAttributePath.h>
#include <app/data-model/DecodableList.h>
#include <app/data-model/List.h>
#include <app/data-model/Nullable.h>
#include <app/util/basic-types.h>
#include <lib/core/TLV.h>
#include <lib/support/BitMask.h>

#include <clusters/shared/Attributes.h>
#include <clusters/shared/Enums.h>
#include <clusters/shared/Structs.h>

#include <clusters/FreshRefrigeratorController/AttributeIds.h>
#include <clusters/FreshRefrigeratorController/ClusterId.h>
#include <clusters/FreshRefrigeratorController/Enums.h>
#include <clusters/FreshRefrigeratorController/Structs.h>

namespace chip {
namespace app {
namespace Clusters {
namespace FreshRefrigeratorController {
namespace Attributes {

namespace FridgeTemperatureDefault {
struct TypeInfo
{
    using Type             = int16_t;
    using DecodableType    = int16_t;
    using DecodableArgType = int16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshRefrigeratorController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::FridgeTemperatureDefault::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace FridgeTemperatureDefault
namespace FreezerTemperatureDefault {
struct TypeInfo
{
    using Type             = int16_t;
    using DecodableType    = int16_t;
    using DecodableArgType = int16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshRefrigeratorController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::FreezerTemperatureDefault::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace FreezerTemperatureDefault
namespace FridgePreviousTemperature {
struct TypeInfo
{
    using Type             = int16_t;
    using DecodableType    = int16_t;
    using DecodableArgType = int16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshRefrigeratorController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::FridgePreviousTemperature::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace FridgePreviousTemperature
namespace FreezerPreviousTemperature {
struct TypeInfo
{
    using Type             = int16_t;
    using DecodableType    = int16_t;
    using DecodableArgType = int16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshRefrigeratorController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::FreezerPreviousTemperature::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace FreezerPreviousTemperature
namespace SuperCoolTime {
struct TypeInfo
{
    using Type             = uint32_t;
    using DecodableType    = uint32_t;
    using DecodableArgType = uint32_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshRefrigeratorController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::SuperCoolTime::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace SuperCoolTime
namespace SuperFreezeTime {
struct TypeInfo
{
    using Type             = uint32_t;
    using DecodableType    = uint32_t;
    using DecodableArgType = uint32_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshRefrigeratorController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::SuperFreezeTime::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace SuperFreezeTime
namespace AlarmTime {
struct TypeInfo
{
    using Type             = uint32_t;
    using DecodableType    = uint32_t;
    using DecodableArgType = uint32_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshRefrigeratorController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::AlarmTime::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace AlarmTime
namespace ResetTimeout {
struct TypeInfo
{
    using Type             = uint32_t;
    using DecodableType    = uint32_t;
    using DecodableArgType = uint32_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshRefrigeratorController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::ResetTimeout::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace ResetTimeout
namespace DisplayActiveTime {
struct TypeInfo
{
    using Type             = uint32_t;
    using DecodableType    = uint32_t;
    using DecodableArgType = uint32_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshRefrigeratorController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::DisplayActiveTime::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace DisplayActiveTime
namespace DisplayErrorTime {
struct TypeInfo
{
    using Type             = uint32_t;
    using DecodableType    = uint32_t;
    using DecodableArgType = uint32_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshRefrigeratorController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::DisplayErrorTime::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace DisplayErrorTime
namespace CompressorState {
struct TypeInfo
{
    using Type             = bool;
    using DecodableType    = bool;
    using DecodableArgType = bool;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshRefrigeratorController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::CompressorState::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace CompressorState
namespace DefrostState {
struct TypeInfo
{
    using Type             = bool;
    using DecodableType    = bool;
    using DecodableArgType = bool;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshRefrigeratorController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::DefrostState::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace DefrostState
namespace FridgeErrorMargin {
struct TypeInfo
{
    using Type             = int16_t;
    using DecodableType    = int16_t;
    using DecodableArgType = int16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshRefrigeratorController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::FridgeErrorMargin::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace FridgeErrorMargin
namespace FreezerErrorMargin {
struct TypeInfo
{
    using Type             = int16_t;
    using DecodableType    = int16_t;
    using DecodableArgType = int16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshRefrigeratorController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::FreezerErrorMargin::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace FreezerErrorMargin
namespace TemperatureErrorTime {
struct TypeInfo
{
    using Type             = uint32_t;
    using DecodableType    = uint32_t;
    using DecodableArgType = uint32_t;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshRefrigeratorController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::TemperatureErrorTime::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace TemperatureErrorTime
namespace FridgeDoorState {
struct TypeInfo
{
    using Type             = bool;
    using DecodableType    = bool;
    using DecodableArgType = bool;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshRefrigeratorController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::FridgeDoorState::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace FridgeDoorState
namespace FreezerDoorState {
struct TypeInfo
{
    using Type             = bool;
    using DecodableType    = bool;
    using DecodableArgType = bool;

    static constexpr ClusterId GetClusterId() { return Clusters::FreshRefrigeratorController::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::FreezerDoorState::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace FreezerDoorState
namespace GeneratedCommandList {
struct TypeInfo : public Clusters::Globals::Attributes::GeneratedCommandList::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::FreshRefrigeratorController::Id; }
};
} // namespace GeneratedCommandList
namespace AcceptedCommandList {
struct TypeInfo : public Clusters::Globals::Attributes::AcceptedCommandList::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::FreshRefrigeratorController::Id; }
};
} // namespace AcceptedCommandList
namespace AttributeList {
struct TypeInfo : public Clusters::Globals::Attributes::AttributeList::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::FreshRefrigeratorController::Id; }
};
} // namespace AttributeList
namespace FeatureMap {
struct TypeInfo : public Clusters::Globals::Attributes::FeatureMap::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::FreshRefrigeratorController::Id; }
};
} // namespace FeatureMap
namespace ClusterRevision {
struct TypeInfo : public Clusters::Globals::Attributes::ClusterRevision::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::FreshRefrigeratorController::Id; }
};
} // namespace ClusterRevision

struct TypeInfo
{
    struct DecodableType
    {
        static constexpr ClusterId GetClusterId() { return Clusters::FreshRefrigeratorController::Id; }

        CHIP_ERROR Decode(TLV::TLVReader & reader, const ConcreteAttributePath & path);

        Attributes::FridgeTemperatureDefault::TypeInfo::DecodableType fridgeTemperatureDefault     = static_cast<int16_t>(0);
        Attributes::FreezerTemperatureDefault::TypeInfo::DecodableType freezerTemperatureDefault   = static_cast<int16_t>(0);
        Attributes::FridgePreviousTemperature::TypeInfo::DecodableType fridgePreviousTemperature   = static_cast<int16_t>(0);
        Attributes::FreezerPreviousTemperature::TypeInfo::DecodableType freezerPreviousTemperature = static_cast<int16_t>(0);
        Attributes::SuperCoolTime::TypeInfo::DecodableType superCoolTime                           = static_cast<uint32_t>(0);
        Attributes::SuperFreezeTime::TypeInfo::DecodableType superFreezeTime                       = static_cast<uint32_t>(0);
        Attributes::AlarmTime::TypeInfo::DecodableType alarmTime                                   = static_cast<uint32_t>(0);
        Attributes::ResetTimeout::TypeInfo::DecodableType resetTimeout                             = static_cast<uint32_t>(0);
        Attributes::DisplayActiveTime::TypeInfo::DecodableType displayActiveTime                   = static_cast<uint32_t>(0);
        Attributes::DisplayErrorTime::TypeInfo::DecodableType displayErrorTime                     = static_cast<uint32_t>(0);
        Attributes::CompressorState::TypeInfo::DecodableType compressorState                       = static_cast<bool>(0);
        Attributes::DefrostState::TypeInfo::DecodableType defrostState                             = static_cast<bool>(0);
        Attributes::FridgeErrorMargin::TypeInfo::DecodableType fridgeErrorMargin                   = static_cast<int16_t>(0);
        Attributes::FreezerErrorMargin::TypeInfo::DecodableType freezerErrorMargin                 = static_cast<int16_t>(0);
        Attributes::TemperatureErrorTime::TypeInfo::DecodableType temperatureErrorTime             = static_cast<uint32_t>(0);
        Attributes::FridgeDoorState::TypeInfo::DecodableType fridgeDoorState                       = static_cast<bool>(0);
        Attributes::FreezerDoorState::TypeInfo::DecodableType freezerDoorState                     = static_cast<bool>(0);
        Attributes::GeneratedCommandList::TypeInfo::DecodableType generatedCommandList;
        Attributes::AcceptedCommandList::TypeInfo::DecodableType acceptedCommandList;
        Attributes::AttributeList::TypeInfo::DecodableType attributeList;
        Attributes::FeatureMap::TypeInfo::DecodableType featureMap           = static_cast<uint32_t>(0);
        Attributes::ClusterRevision::TypeInfo::DecodableType clusterRevision = static_cast<uint16_t>(0);
    };
};
} // namespace Attributes
} // namespace FreshRefrigeratorController
} // namespace Clusters
} // namespace app
} // namespace chip
