/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Attributes.ipp.zapt

#include <clusters/FreshRefrigeratorController/Attributes.h>

#include <app/data-model/Decode.h>
#include <app/data-model/WrappedStructEncoder.h>

namespace chip {
namespace app {
namespace Clusters {
namespace FreshRefrigeratorController {
namespace Attributes {
CHIP_ERROR TypeInfo::DecodableType::Decode(TLV::TLVReader & reader, const ConcreteAttributePath & path)
{
    switch (path.mAttributeId)
    {
    case Attributes::FridgeTemperatureDefault::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, fridgeTemperatureDefault);
    case Attributes::FreezerTemperatureDefault::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, freezerTemperatureDefault);
    case Attributes::FridgePreviousTemperature::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, fridgePreviousTemperature);
    case Attributes::FreezerPreviousTemperature::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, freezerPreviousTemperature);
    case Attributes::SuperCoolTime::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, superCoolTime);
    case Attributes::SuperFreezeTime::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, superFreezeTime);
    case Attributes::AlarmTime::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, alarmTime);
    case Attributes::ResetTimeout::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, resetTimeout);
    case Attributes::DisplayActiveTime::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, displayActiveTime);
    case Attributes::DisplayErrorTime::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, displayErrorTime);
    case Attributes::CompressorState::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, compressorState);
    case Attributes::DefrostState::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, defrostState);
    case Attributes::FridgeErrorMargin::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, fridgeErrorMargin);
    case Attributes::FreezerErrorMargin::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, freezerErrorMargin);
    case Attributes::TemperatureErrorTime::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, temperatureErrorTime);
    case Attributes::FridgeDoorState::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, fridgeDoorState);
    case Attributes::FreezerDoorState::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, freezerDoorState);
    case Attributes::DefrostTemperature::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, defrostTemperature);
    case Attributes::GeneratedCommandList::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, generatedCommandList);
    case Attributes::AcceptedCommandList::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, acceptedCommandList);
    case Attributes::AttributeList::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, attributeList);
    case Attributes::FeatureMap::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, featureMap);
    case Attributes::ClusterRevision::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, clusterRevision);
    default:
        return CHIP_NO_ERROR;
    }
}
} // namespace Attributes
} // namespace FreshRefrigeratorController
} // namespace Clusters
} // namespace app
} // namespace chip
