/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Enums.h.zapt

#pragma once

#include <clusters/shared/Enums.h>
#include <cstdint>

namespace chip {
namespace app {
namespace Clusters {
namespace MideaAirConditionerAlarmTest {

// Bitmap for AlarmBitmap
enum class AlarmBitmap : uint32_t
{
    kInteriorBoardCommunicationFailure                       = 0x1,
    kIndoorMainControlBoardFailure                           = 0x2,
    kIndoorOutdoorBoardCommunicationFailure                  = 0x4,
    kZeroCrossingDetectionFailure                            = 0x8,
    kIndoorBoardFanStallFailure                              = 0x10,
    kOutdoorCondenserSensorFailure                           = 0x20,
    kOutdoorAmbientTemperatureSensorFailure                  = 0x40,
    kOutdoorCompressionEngineExhaustTemperatureSensorFailure = 0x80,
    kOutdoorESideFailure                                     = 0x100,
    kIndoorTemperatureSensorFailure                          = 0x200,
    kIndoorEvaporatorTemperatureSensorFailure                = 0x400,
    kOutdoorWindSpeedStallFailure                            = 0x800,
    kIpmModuleProtection                                     = 0x1000,
    kVoltageProtection                                       = 0x2000,
    kOutdoorCompressorTopTemperatureProtection               = 0x4000,
    kOutdoorTemperatureLowProtection                         = 0x8000,
    kCompressorPositionProtection                            = 0x10000,
    kDisplayBoardESideFault                                  = 0x20000,
    kOuterPipeTemperatureProtection                          = 0x40000,
    kExhaustHighTemperatureProtection                        = 0x80000,
    kHeatingAndColdWindProtection                            = 0x100000,
    kCurrentProtection                                       = 0x200000,
    kEvaporatorHighAndLowTemperatureProtection               = 0x400000,
    kCondenserHighAndLowTemperatureProtectionFrequencyLimit  = 0x800000,
    kExhaustHighAndLowTemperatureProtection                  = 0x1000000,
    kIndoorOutdoorCommunicationMismatchProtocol              = 0x2000000,
    kRefrigerantLeakageProtection                            = 0x4000000,
};

// Bitmap for Feature
enum class Feature : uint32_t
{
    kReset = 0x1,
};
} // namespace MideaAirConditionerAlarmTest
} // namespace Clusters
} // namespace app
} // namespace chip
